# Quick test configuration - 50 iterations for fast testing

# Test Cases:
#   test_case_a: Sphere → Ellipsoid (Easy - uniform stretch)
#   test_case_b: Sphere → Bump (Medium - local deformation)
#   test_case_c: Sphere → Complex (Hard - multiple deformations)
test_case: "test_case_c"

mesh:
  subdivision_level: 2  # 0=12v, 1=42v, 2=162v, 3=642v, 4=2562v, 5=10242v
  initial_type: "sphere"  # Only 'sphere' implemented (ellipsoid, custom [NOT IMPLEMENTED YET])

optimization:
  num_iterations: 50  # Quick test
  learning_rate: 0.01
  optimizer: "adam"
  use_scheduler: false  # [NOT IMPLEMENTED YET]

losses:
  silhouette_weight: 1.0
  edge_weight: 0.1
  laplacian_weight: 0.1
  normal_weight: 0.01
  adaptive_regularization: true
  silhouette_type: "mse"  # Options: mse, bce (both implemented)

rendering:
  image_size: 256
  blur_radius: 0.01  # Blur for soft differentiable rendering (try 0.001-0.01)
  target_rendering_mode: "both"  # Options: "soft", "hard", "both"

# NOTE: Camera settings are loaded from test case data (camera_config.json)
# To configure cameras for test case generation, edit data/generation_config.yaml

visualization:
  log_every: 10
  save_checkpoint_every: 25
  checkpoint_mode: "percentage"  # Options: "percentage" (0-100) or "iteration" (every N iterations)
  save_checkpoint_renders: true  # NEW: Save multi-angle renders at checkpoints
  checkpoint_render_views: 4     # NEW: Number of viewing angles
  save_video: false  # Disable for quick test
  video_fps: 10
  plot_loss_curves: true
  create_comparison: true
  verbose: true  # Controls detailed console output

output:
  base_dir: "results"
  experiment_name: "quick_test"
  save_intermediate: true
  save_history: true

device:
  type: "auto"
  cuda_device: 0

advanced:
  use_grad_clip: false  # [NOT IMPLEMENTED YET]
  use_early_stopping: false  # [NOT IMPLEMENTED YET]
  random_seed: 42
  use_vertex_bounds: true
  vertex_bound_min: -5.0
  vertex_bound_max: 5.0

evaluation:
  compute_chamfer: true
  compute_normal_consistency: true
  compute_edge_length_variance: true
  save_evaluation_report: true
